version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    platform: linux/amd64
    environment:
      POSTGRES_DB: sector
      POSTGRES_USER: sector_user
      POSTGRES_PASSWORD: sector_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sector_user -d sector"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: linux/amd64
        TARGETPLATFORM: linux/amd64
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sector
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: sector_user
      SPRING_DATASOURCE_PASSWORD: sector_password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  postgres_data:
