spring:
  application:
    name: Sector
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./data/sector;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h

# OpenAPI Configuration
sector:
  openapi:
    dev-url: http://localhost:8080

# Swagger UI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
